from .apis_estoque import listar_local_estoque
from .apis_estoque import incluir_ajuste_estoque
from .apis_estoque import diferenca_quantidade_estoque_produto
from .apis_projetos import listar_projetos
from .apis_projetos import get_cod_projeto
from .apis_produtos import pesquisar_produto_cod_func
from .apis_produtos import pesquisar_produto_nome_func
from .apis_produtos import listar_produtos
from .apis_produtos import listar_produtos_codigo_produto
from .apis_produtos import relatorio_quant_diferenca_func
from .apis_vendas import incluir_pedido_venda
from .apis_vendas import incluir_pedido_venda_lot
from .apis_cliente import get_cod_cliente
from .apis_cliente import listar_clientes
from .apis_departamentos import listar_departamentos
